### ISSUE TITLE
Opening menu on the top bar then click other options on the top bar closes it.

### ISSUE THREAD

**Issue by ryantm** [NightWhistler/PageTurner#202]
Seen on my Nexus 7 in 296597e2e0ab8faf5abc620a2111f3db6f7aeec1  

To reproduce, tap screen to reveal top bar, tap the vertical triple dot to open the menu. tap the gear to try to open preferences. Instead the top bar disappears.

What I am expecting to happen: the preferences open.

**Comment by NightWhistler** [comment]
Closing it since the preferences have been moved to the navigation drawer.
