### ISSUE TITLE
Unable to compile the project in latest Android Studio gradle.

### ISSUE THREAD

**Issue by sumanabhi** [NightWhistler/PageTurner#597]
Hi, 

I am facing this issue while compilation your repo into the latest android studio 3.0.1 and getting
this error -
`Unsupported method: BaseConfig.getApplicationIdSuffix().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.`

while in the android studio version 2.3.3, it is working fine but since my live project is on the newer Gradle version. 

So, as I need to import it as a module if I will be able to compile on the newer one.

Please help me out It's Urgent.

**Comment by ycsghr** [comment]
Same idea, have you solved it?

**Comment by ycsghr** [comment]
Error:(24, 0) Gradle version 2.2 is required. Current version is 4.4.

Please fix the project's Gradle settings.
<a href="fixGradleVersionInWrapper">Fix Gradle wrapper and re-import project</a><br><a href="openGradleSettings">Gradle settings</a>

**Comment by ycsghr** [comment]
It's urgent to wait online

**Comment by sumanabhi** [comment]
So have you tried to change your Gradle Settings?

**Comment by sumanabhi** [comment]
I have customized & migrated it to make successfully build of the project. If you wish I can share the repo to your email id. 

P.S. :- if yes , share your mail id.

**Comment by ycsghr** [comment]
Wait a minute, I'll find my mailbox. It's been a long time since I got it

**Comment by ycsghr** [comment]
ysam37424@gmail.com

**Comment by ycsghr** [comment]
Thank You

**Comment by ycsghr** [comment]
I've changed these places and I'm still compiling
![tim 20180913144955](https://user-images.githubusercontent.com/34826145/45471896-16638180-b765-11e8-9997-eb541ea32199.png)
![tim 20180913145006](https://user-images.githubusercontent.com/34826145/45471897-16638180-b765-11e8-9e13-265b2a47a00a.png)
![tim 20180913145019](https://user-images.githubusercontent.com/34826145/45471898-16fc1800-b765-11e8-85c0-c1874e7655ec.png)

**Comment by ycsghr** [comment]
![image](https://user-images.githubusercontent.com/34826145/45474575-b07af800-b76c-11e8-897c-b3c790618d1d.png)
I don't know what to write here it always conflicts with apply plugin: 'robolectric'

**Comment by ycsghr** [comment]
Error:(26, 0) Cannot add a configuration with name 'testCompile' as a configuration with that name already exists.
<a href="openFile:D:\PageTurner-master\build.gradle">Open File</a>

**Comment by sumanabhi** [comment]
I have just uploaded the whole customized Project with new Gradle.

Please check it successfully compiled.
[https://github.com/sumanabhi/PageTurner](https://github.com/sumanabhi/PageTurner)

**Comment by ycsghr** [comment]
Computer crashes...

**Comment by sumanabhi** [comment]
Sorry, what you want to say I don't Understand.

I have uploaded here after checking Successful Compilation on My System.
Android Studio:- 3.1.4

**Comment by ycsghr** [comment]
I am now compiling with Android Studio3.0.1, sorry, my English level may be a bit poor

**Comment by ycsghr** [comment]
How do you put it into your project?

**Comment by sumanabhi** [comment]
Just clone it. It works. otherwise you can ping me on 
live:abhi.suman

**Comment by ycsghr** [comment]
I am compiling him now. Today, the computer doesn’t know what’s going on.

**Comment by ycsghr** [comment]
![qq 20180913211033](https://user-images.githubusercontent.com/34826145/45490974-1bdbbe80-b79b-11e8-8e49-15a8d6d4f79b.png)
I added this here to solve the problem that it can only display half of the screen after searching.

**Comment by ycsghr** [comment]
But I have a new problem now. The picture shows the problem. I don't know where he has a problem that caused the bug.
![qq 20180913214011](https://user-images.githubusercontent.com/34826145/45491958-9dcce700-b79d-11e8-8ce1-dbcb73a7a4a7.jpg)

**Comment by ycsghr** [comment]
The picture above is not complete and the pictures overlap.

**Comment by ycsghr** [comment]
If you are interested in solving this bug, you can leave your email and send me this epub file.

**Comment by jayesh28589** [comment]
@NightWhistler :  Hello Alex Kuiper, Please update the library for latest android studio 3.1 +, It is taking too much time to update it, If you can update it then It would be great.

thanks.

**Comment by jeanlinux** [comment]
> I have customized & migrated it to make successfully build of the project. If you wish I can share the repo to your email id.
> 
> P.S. :- if yes , share your mail id.

@sumanabhi  can you please share you fixed repo with me

**Comment by jayesh28589** [comment]
@jeanlinux : thanks for the update, My email id is Jayesh.it2011@gmail.com, you can foreword it there.
Thanks.

**Comment by NightWhistler** [comment]
@sumanabhi I took a look through your repo, hoping to be able to ask you for a pull request.

It looks like your commit contains a lot of different changes as well though. If you could send a pull request with just the Gradle build fixes I would appreciate it a lot.

@jayesh28589 @jeanlinux I'm sorry, but I personally don't have time to work on PageTurner anymore. I will merge pull requests that are sent to me, but I won't do any active development in the near future.

**Comment by sumanabhi** [comment]
@NightWhistler Sure Sorry actually due to some issue with my account i am not able to use it.

I will create PR for the same even if it goes well with the recent version.

Give me some time.

**Comment by sumanabhi** [comment]
> @sumanabhi can you please share you fixed repo with me... email is [jeanlinux5@gmail.co](mailto:jeanlinux5@gmail.com)

This is the link where the successfully compiled build was there but i don't have too much time to check with the recent versions.

https://github.com/sumanabhi/PageTurner

Will check once i got free from all this.

**Comment by sumanabhi** [comment]
Hi @NightWhistler,

I got some time and just look into this and changed the Gradle Version to enable this project to work with the Latest Android Studio 4.1.2

But I am not able to push into this repo as I have not written access.

Kindly give me access or let me know how can I Create the PR.

**Comment by sumanabhi** [comment]
Hi @NightWhistler,

I created PR with the only change of Gradle fix so that it can compile successfully and run as well.
