### ISSUE TITLE
Can't import this in android studio 3.1.4

### ISSUE THREAD

**Issue by jayesh28589** [NightWhistler/PageTurner#598]
Hello guys,

I can't import this project in android studio, there are so many issues coming when I run the app in device.

@hanjiang-stanford : Please update this project to support latest android version 28.

Thanks.

**Comment by jeanlinux** [comment]
The app can not run in android studio as @jayesh28589  stated above,many issues with gradle (old version) @NightWhistler can you please update this app to support latest android version 28.
thanks in advance

**Comment by sumanabhi** [comment]
You can now import. 

The updated Gradle version with all the compatibility is merged in this PR https://github.com/NightWhistler/PageTurner/pull/600
