### ISSUE TITLE
F-Droid Version?

### ISSUE THREAD

**Issue by xeruf** [NightWhistler/PageTurner#601]
There is a version on F-Droid which has not been updated in years, what happened there?
https://f-droid.org/en/packages/net.nightwhistler.pageturner/
I saw there is now a dual license, so does this not fulfill FOSS criteria anymore?

**Comment by NightWhistler** [comment]
The dual license has been there since the start. 

PageTurner hasn't been under active development for many years now, but you're right that the version on F-droid is old.
I don't really know whey they never built the 2.2.6 and 2.3.0 versions
